language: haxe

haxe:
  - 3.4.7

sudo: false

install:
  - haxelib install snowfall > log.txt || cat log.txt
  - haxelib run snowfall update luxe > log.txt || cat log.txt
  - haxelib list > log.txt || cat log.txt

script:
  - haxelib run flow build web

deploy:
  provider: pages
  local-dir: /bin/web/
  email: $email
  name: $name
  skip-cleanup: true
  github-token: $GITHUB_TOKEN 
  keep-history: true
  on:
    branch: master
cache:
  directories:
   - $HOME/haxe/lib